# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure CryptPad paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ cryptpad_uid }}"
    group: "{{ cryptpad_gid }}"
  with_items:
    - "{{ cryptpad_base_path }}"
    - "{{ cryptpad_data_root_path }}"
    - "{{ cryptpad_customize_path }}"
    - "{{ cryptpad_block_path }}"
    - "{{ cryptpad_data_path }}"
    - "{{ cryptpad_files_path }}"
    - "{{ cryptpad_blob_path }}"

- name: Ensure CryptPad support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ cryptpad_base_path }}/{{ item }}"
    mode: 0640
    owner: "{{ cryptpad_uid }}"
    group: "{{ cryptpad_gid }}"
  with_items:
    - env
    - labels
    - config.js

- name: Run if self-building of CryptPad container image is not enabled
  when: "not cryptpad_container_image_self_build | bool"
  block:
    - name: Ensure CryptPad container image is pulled via community.docker.docker_image
      when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
      community.docker.docker_image:
        name: "{{ cryptpad_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
        force_source: "{{ cryptpad_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else cryptpad_container_image_force_pull }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed

    - name: Ensure CryptPad container image is pulled via ansible.builtin.command
      when: devture_systemd_docker_base_container_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ cryptpad_container_image }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed
      changed_when: "'Downloaded newer image' in result.stdout"

- name: Run if self-building of CryptPad container image is enabled
  when: "cryptpad_container_image_self_build | bool"
  block:
    - name: Ensure CryptPad repository is present on self-build
      ansible.builtin.git:
        repo: "{{ cryptpad_container_image_self_build_repo }}"
        version: "{{ cryptpad_container_image_self_build_repo_version }}"
        dest: "{{ cryptpad_container_image_self_build_src_files_path }}"
        force: "yes"
      register: cryptpad_git_pull_results

    - name: Ensure CryptPad container image is built
      community.docker.docker_image:
        name: "{{ cryptpad_container_image_self_build_name }}"
        source: build
        force_source: "{{ cryptpad_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else cryptpad_git_pull_results.changed }}"
        build:
          dockerfile: Dockerfile
          path: "{{ cryptpad_container_image_self_build_src_files_path }}"
          pull: true
          args:




- name: Ensure CryptPad container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ cryptpad_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure CryptPad container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ cryptpad_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure CryptPad systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/cryptpad.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ cryptpad_identifier }}.service"
    mode: "0644"
