# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of CryptPad systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ cryptpad_identifier }}.service"
  register: cryptpad_service_stat

- name: Uninstall CryptPad systemd services and files
  when: cryptpad_service_stat.stat.exists | bool
  block:
    - name: Ensure CryptPad systemd service is stopped
      ansible.builtin.service:
        name: "{{ cryptpad_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure CryptPad systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ cryptpad_identifier }}.service"
        state: absent

    - name: Ensure CryptPad path does not exist
      ansible.builtin.file:
        path: "{{ cryptpad_base_path }}"
        state: absent
