# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "cryptpad_http_header_content_permission_policy", "new": "cryptpad_http_header_permissions_policy" }

- name: Fail if required CryptPad settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - cryptpad_identifier
    - cryptpad_uid
    - cryptpad_gid
    - cryptpad_main_hostname
    - cryptpad_sandbox_hostname

- name: Run if Traefik is enabled
  when: cryptpad_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for CryptPad are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - cryptpad_main_container_labels_traefik_hostname
        - cryptpad_sandbox_container_labels_traefik_hostname
